data:
  path: "data/"
  train: "trainset_28spk_wav"
  test: "testset_wav"

train:
  epochs: 50
  batch_size: 16
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  output_path: "results/semgan"
  model_name: "semgan"
  checkpoint_path: null  # "/path/to/checkpoint.pt"

wandb:
  project: "semgan_project"
  tags:
    - "debug"
  notes: "Training with default configuration"
  entity: ""
